// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18lmayf7Bv5z-VXoRZ2XTriHtpu7rg_s',
    appId: '1:168630501276:web:4a1fc3da35bf75dc8bd259',
    messagingSenderId: '168630501276',
    projectId: 'my-chat-4a335',
    authDomain: 'my-chat-4a335.firebaseapp.com',
    storageBucket: 'my-chat-4a335.appspot.com',
    measurementId: 'G-QDC1Y4H6BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0dZQv94r-j5rpF5BuQUFk05ELuefIrjE',
    appId: '1:168630501276:android:6feacb51c6879a668bd259',
    messagingSenderId: '168630501276',
    projectId: 'my-chat-4a335',
    storageBucket: 'my-chat-4a335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCguABzji18azaJv93QNkZRbv8vqPgMtzk',
    appId: '1:168630501276:ios:dd49ef9105ce63378bd259',
    messagingSenderId: '168630501276',
    projectId: 'my-chat-4a335',
    storageBucket: 'my-chat-4a335.appspot.com',
    androidClientId: '168630501276-vkhl2qa8fno3dhjt0iep2mha6uq45nat.apps.googleusercontent.com',
    iosClientId: '168630501276-t805640iar23u79v4m75t2cgm9ff60dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCguABzji18azaJv93QNkZRbv8vqPgMtzk',
    appId: '1:168630501276:ios:85ae4e745dfb0d058bd259',
    messagingSenderId: '168630501276',
    projectId: 'my-chat-4a335',
    storageBucket: 'my-chat-4a335.appspot.com',
    androidClientId: '168630501276-vkhl2qa8fno3dhjt0iep2mha6uq45nat.apps.googleusercontent.com',
    iosClientId: '168630501276-720443fdlepqi12i450q87ajov8peuhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChat.RunnerTests',
  );
}
